/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-burst_streamer
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_BURST_STREAMER_API_H
#define INCLUDED_BURST_STREAMER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_burst_streamer_EXPORTS
#define BURST_STREAMER_API __GR_ATTR_EXPORT
#else
#define BURST_STREAMER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_BURST_STREAMER_API_H */
