/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(burst_streamer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(be40cffb9ee828b3e62817533f530f7d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <burst_streamer/burst_streamer.h>
// pydoc.h is automatically generated in the build directory
#include <burst_streamer_pydoc.h>

void bind_burst_streamer(py::module& m)
{

    using burst_streamer    = gr::burst_streamer::burst_streamer;


    py::class_<burst_streamer, gr::block, gr::basic_block,
        std::shared_ptr<burst_streamer>>(m, "burst_streamer", D(burst_streamer))

        .def(py::init(&burst_streamer::make),
           D(burst_streamer,make)
        )
        



        ;




}








